export const novelData = {
  title: "The Mysterious Adventure",
  author: "S Plus Studios",
  chapters: [
    {
      title: "CHAPTER I",
      content: `EXCITING NEWS FROM S PLUS STUDIOS!

WE'RE DIVING INTO A BRAND-NEW ADVENTURE! S PLUS STUDIOS IS THRILLED TO ANNOUNCE THAT WE'RE WORKING ON AN ORIGINAL LIGHT NOVEL BRINGING YOU A FRESH STORY FILLED WITH COMPELLING CHARACTERS, RICH WORLD-BUILDING, AND THE HEART-POUNDING ACTION AND EMOTION YOU LOVE.

THIS PROJECT IS COMPLETELY SEPARATE FROM KISHORE AND WILL EXPLORE AN ENTIRELY NEW UNIVERSE—ONE FULL OF MYSTERY, ADVENTURE, AND SURPRISES. STAY TUNED FOR UPDATES, SNEAK PEEKS, AND BEHIND-THE-SCENES CONTENT AS WE BRING THIS EXCITING NEW TALE TO LIFE!

EXCITING NEWS FROM S PLUS STUDIOS!

WE'RE DIVING INTO A BRAND-NEW ADVENTURE! S PLUS STUDIOS IS THRILLED TO ANNOUNCE THAT WE'RE WORKING ON AN ORIGINAL LIGHT NOVEL BRINGING YOU A FRESH STORY FILLED WITH COMPELLING CHARACTERS, RICH WORLD-BUILDING, AND THE HEART-POUNDING ACTION AND EMOTION YOU LOVE.

THE JOURNEY BEGINS IN A SMALL COASTAL TOWN WHERE OUR PROTAGONIST, A YOUNG ARTIST WITH A MYSTERIOUS PAST, DISCOVERS AN ANCIENT ARTIFACT THAT CHANGES EVERYTHING. SUDDENLY THRUST INTO A WORLD OF MAGIC AND DANGER, THEY MUST NAVIGATE NEW ALLIANCES, BETRAYALS, AND THE DISCOVERY OF POWERS THEY NEVER KNEW EXISTED.`,
    },
    {
      title: "CHAPTER II",
      content: `THE ARTIFACT'S SECRET

THE SMALL WOODEN BOX SAT INNOCENTLY ON ELENA'S DESK, ITS SURFACE WORN SMOOTH BY CENTURIES OF HANDLING. SHE'D FOUND IT BURIED IN THE SAND DURING HER MORNING WALK ALONG THE BEACH, HALF-EXPOSED AFTER LAST NIGHT'S STORM.

"WHAT SECRETS DO YOU HOLD?" SHE WHISPERED, TRACING THE INTRICATE CARVINGS WITH HER FINGERTIP. THE SYMBOLS WEREN'T FROM ANY LANGUAGE SHE RECOGNIZED—AND AS THE TOWN'S LIBRARIAN, SHE KNEW MANY.

THE LOCK HAD NO KEYHOLE, JUST A CIRCULAR INDENTATION WITH STRANGE MARKINGS RADIATING OUTWARD LIKE A SUN. ELENA HAD TRIED EVERYTHING TO OPEN IT: PICKS, GENTLE PRESSURE, EVEN HOLDING IT NEAR HEAT IN CASE IT RESPONDED TO TEMPERATURE.

NOTHING WORKED.
`,
    },
    {
      title: "CHAPTER III",
      content: `THE AWAKENING

ELENA GASPED AS THE BLUE LIGHT ENVELOPED HER, WARM AND ELECTRIC AGAINST HER SKIN. THE BOX HOVERED INCHES ABOVE HER PALM, SPINNING SLOWLY, THE SYMBOLS NOW GLOWING WITH AN INNER FIRE.

WORDS FORMED IN HER MIND—NOT ENGLISH, NOT ANY LANGUAGE SHE KNEW—YET SHE UNDERSTOOD THEM PERFECTLY.

"KEEPER," THE VOICE WHISPERED. "AT LAST."

THE ROOM AROUND HER FADED, REPLACED BY VISIONS OF A VAST OCEAN, ISLANDS FLOATING NOT ON WATER BUT IN AIR, CONNECTED BY BRIDGES OF LIGHT. PEOPLE WITH IRIDESCENT SKIN MOVED BETWEEN THEM, SOME WITH WINGS, OTHERS GLIDING ON CURRENTS OF ENERGY.

"WHAT IS THIS?" ELENA TRIED TO SPEAK, BUT HER VOICE MADE NO SOUND. INSTEAD, HER THOUGHTS PROJECTED OUTWARD.

"MEMORIES," THE VOICE ANSWERED. "OF AVALORIA. YOUR ANCESTRAL HOME."`,
    },
    {
      title: "CHAPTER IV",
      content: `HUNTERS IN THE DARK

ELENA HADN'T SLEPT. HOW COULD SHE? THE CRYSTAL FROM THE BOX NOW HUNG FROM A CHAIN AROUND HER NECK, WARM AGAINST HER SKIN, ITS GLOW DIMMED BUT STILL VISIBLE BENEATH HER CLOTHING.

THE MORNING LIGHT BROUGHT NO CLARITY TO THE PREVIOUS NIGHT'S REVELATIONS. AVALORIA. ANCESTRAL HOME. LAST DESCENDANT. THE WORDS ECHOED IN HER MIND AS SHE MOVED MECHANICALLY THROUGH HER MORNING ROUTINE.

AT THE LIBRARY, SHE PULLED EVERY BOOK ON ANCIENT CIVILIZATIONS, LOST CONTINENTS, MYTHS OF FLYING ISLANDS. NOTHING MATCHED WHAT SHE'D SEEN.

IT WAS NEAR CLOSING TIME WHEN SHE FELT IT—A COLD PRICKLING AT THE BACK OF HER NECK. SOMEONE WAS WATCHING HER.

AT THE REFERENCE DESK, A MAN IN A CHARCOAL SUIT STOOD PERFECTLY STILL, HIS EYES FIXED ON HER. TOO STILL. UNNATURALLY SO. NO ONE ELSE SEEMED TO NOTICE HIM, WALKING PAST AS IF HE WEREN'T THERE.`,
    },
    {
      title: "CHAPTER V",
      content: `UNEXPECTED ALLIES

ELENA RACED THROUGH THE BACK STREETS OF HARBORVIEW, THE EVENING FOG ROLLING IN FROM THE SEA, SHROUDING HER PATH. THE CRYSTAL PULSED AGAINST HER SKIN, SOMEHOW GUIDING HER, URGING HER TOWARD THE OLD LIGHTHOUSE AT THE EDGE OF TOWN.

SHE RISKED A GLANCE BACK. THREE FIGURES NOW, ALL IN IDENTICAL SUITS, MOVING WITH THAT SAME UNNATURAL GRACE. NOT RUNNING, BUT GAINING NONETHELESS.

THE LIGHTHOUSE LOOMED AHEAD, ABANDONED FOR DECADES, ITS LIGHT LONG EXTINGUISHED. ELENA HAD PLAYED THERE AS A CHILD, KNEW ITS TWISTING STAIRS AND HIDDEN CORNERS. IF SHE COULD JUST REACH IT—

A HAND GRABBED HER ARM, PULLING HER SIDEWAYS INTO AN ALLEY. ELENA OPENED HER MOUTH TO SCREAM, BUT ANOTHER HAND CLAMPED OVER IT.

"QUIET," A VOICE HISSED IN HER EAR. "THEY TRACK BY SOUND AND MOVEMENT."

HER CAPTOR DRAGGED HER DEEPER INTO THE SHADOWS. ELENA STRUGGLED UNTIL SHE CAUGHT SIGHT OF HER "ATTACKER"—A YOUNG MAN ABOUT HER AGE, WITH STRANGE AMBER EYES THAT SEEMED TO GLOW IN THE DARKNESS.
"`,
    },
    {
      title: "CHAPTER VI",
      content: `THE LIGHTHOUSE SANCTUARY

"TRUST YOU?" ELENA WHISPERED INCREDULOUSLY. "I DON'T EVEN KNOW YOU!"

KIAN'S AMBER EYES FLASHED WITH IMPATIENCE. "YOU DON'T KNOW THEM EITHER," HE NODDED TOWARD THE STREET WHERE SHADOWS MOVED AGAINST THE FOG. "BUT I CAN TELL YOU THEY'RE VOID SENTINELS, HUNTERS FROM THE SPACE BETWEEN WORLDS. AND THEY'RE HERE FOR THE HEART OF AVALORIA THAT YOU'RE WEARING AROUND YOUR NECK."

ELENA'S HAND INSTINCTIVELY CLUTCHED THE CRYSTAL. "HOW DO YOU—"

"THERE'S NO TIME," KIAN CUT HER OFF. "THE LIGHTHOUSE IS A NEXUS POINT, A THIN PLACE BETWEEN YOUR WORLD AND OTHERS. WE CAN USE IT, BUT WE HAVE TO REACH IT FIRST."

A HIGH, THIN SOUND PIERCED THE AIR—LIKE METAL SCRAPING AGAINST GLASS. THE VOID SENTINELS WERE CALLING TO EACH OTHER.

"THEY'VE PICKED UP OUR TRAIL," KIAN MUTTERED. HE REACHED INTO HIS JACKET AND PULLED OUT WHAT LOOKED LIKE A SMOOTH RIVER STONE, ETCHED WITH SYMBOLS SIMILAR TO THOSE ON ELENA'S BOX. "HOLD ONTO ME."

ELENA HESITATED ONLY A MOMENT BEFORE GRIPPING HIS OUTSTRETCHED ARM. KIAN SQUEEZED THE STONE, AND IT BEGAN TO GLOW WITH A GOLDEN LIGHT."`,
    },
  ],
}
